export const categoryConstants = {
  GET_CATEGORY_REQUEST: "GET_CATEGORY_REQUEST",
  GET_CATEGORY_REQUEST_SUCCESS: "GET_CATEGORY_REQUEST_SUCCESS",
  GET_CATEGORY_REQUEST_FAILURE: "GET_CATEGORY_REQUEST_FAILURE",
};

export const productConstants = {
  GET_PRODUCT_REQUEST: "GET_PRODUCT_REQUEST",
  GET_PRODUCT_REQUEST_SUCCESS: "GET_PRODUCT_REQUEST_SUCCESS",
  GET_PRODUCT_REQUEST_FAILURE: "GET_PRODUCT_REQUEST_FAILURE",
  GET_PRODUCT_BY_SLUG_REQUEST: "GET_PRODUCT_BY_SLUG_REQUEST",
  GET_PRODUCT_BY_SLUG_REQUEST_SUCCESS: "GET_PRODUCT_BY_SLUG_REQUEST_SUCCESS",
  GET_PRODUCT_BY_SLUG_REQUEST_FAILURE: "GET_PRODUCT_BY_SLUG_REQUEST_FAILURE",
};
